### ISSUE TITLE
Build Error while building mvfst

### ISSUE THREAD

**Issue by Zidan241** [facebookresearch/mvfst-rl#28]
Hello, i have been having problems while building this library on my Ubuntu 18.04.5 LTS, but most were build errors for mvfst, espicially while building folly and fizz libraries; some of which where because i did not have google tests installed on my anaconda environment, after that this error showed up and i cannot find a solution for it, i would appreciate any assistance.
I made sure a couple of times that the problem is not from my end, could it be because the library is 2 years old, perhaps there is a dependency compatibility problem?
***
here is the last lines of the ouput showing the error after running setup.sh:
```
CMake Warning at quic/tools/tperf/CMakeLists.txt:10 (add_executable):
  Cannot generate a safe runtime search path for target tperf because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libz.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/mohamed/anaconda3/envs/mvfst-rl/lib
    runtime library [libssl.so.1.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/mohamed/anaconda3/envs/mvfst-rl/lib
    runtime library [libcrypto.so.1.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/mohamed/anaconda3/envs/mvfst-rl/lib
    runtime library [liblzma.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/mohamed/anaconda3/envs/mvfst-rl/lib
    runtime library [liblz4.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/mohamed/anaconda3/envs/mvfst-rl/lib

  Some of these libraries may not be found correctly.


-- Generating done
-- Build files have been written to: /home/mohamed/Desktop/Bachelor/mvfst-rl/third-party/mvfst/_build/build
+ make -j 4
[  0%] Built target mvfst_constants
[  1%] Built target mvfst_bufutil
[  1%] Performing update step for 'googletest'
[  2%] Built target mvfst_exception
[  3%] Built target mvfst_looper
[  6%] Built target mvfst_codec_types
[  7%] No patch step for 'googletest'
[  8%] Built target mvfst_codec_decode
[  8%] Performing configure step for 'googletest'
loading initial cache file /home/mohamed/Desktop/Bachelor/mvfst-rl/third-party/mvfst/_build/build/googletest/tmp/googletest-cache-RelWithDebInfo.cmake
[  8%] Built target mvfst_codec_packet_number_cipher
[  8%] Building CXX object quic/handshake/CMakeFiles/mvfst_handshake.dir/QuicFizzFactory.cpp.o
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mohamed/Desktop/Bachelor/mvfst-rl/third-party/mvfst/_build/build/googletest/src/googletest-build
[  8%] Performing build step for 'googletest'
[ 36%] Built target gmock_main
[ 54%] Built target gtest
[ 81%] Built target gmock
[100%] Built target gtest_main
[  8%] No install step for 'googletest'
[  9%] Completed 'googletest'
[ 10%] Built target googletest
Scanning dependencies of target QuicConnectionIdTest
Scanning dependencies of target PacketNumberTest
Scanning dependencies of target QuicIntegerTest
[ 11%] Building CXX object quic/codec/test/CMakeFiles/QuicIntegerTest.dir/QuicIntegerTest.cpp.o
[ 11%] Building CXX object quic/codec/test/CMakeFiles/QuicConnectionIdTest.dir/QuicConnectionIdTest.cpp.o
[ 11%] Building CXX object quic/codec/test/CMakeFiles/PacketNumberTest.dir/PacketNumberTest.cpp.o
/home/mohamed/Desktop/Bachelor/mvfst-rl/third-party/mvfst/quic/handshake/QuicFizzFactory.cpp:17:37: error: ‘folly::Optional<fizz::TLSMessage> {anonymous}::QuicPlaintextReadRecordLayer::read(folly::IOBufQueue&)’ marked ‘override’, but does not override
   folly::Optional<fizz::TLSMessage> read(folly::IOBufQueue& buf) override {
                                     ^~~~
/home/mohamed/Desktop/Bachelor/mvfst-rl/third-party/mvfst/quic/handshake/QuicFizzFactory.cpp:17:37: warning:   by ‘folly::Optional<fizz::TLSMessage> {anonymous}::QuicPlaintextReadRecordLayer::read(folly::IOBufQueue&)’ [-Woverloaded-virtual]
/home/mohamed/Desktop/Bachelor/mvfst-rl/third-party/mvfst/quic/handshake/QuicFizzFactory.cpp:35:37: error: ‘folly::Optional<fizz::TLSMessage> {anonymous}::QuicEncryptedReadRecordLayer::read(folly::IOBufQueue&)’ marked ‘override’, but does not override
   folly::Optional<fizz::TLSMessage> read(folly::IOBufQueue& buf) override {
                                     ^~~~
/home/mohamed/Desktop/Bachelor/mvfst-rl/third-party/mvfst/quic/handshake/QuicFizzFactory.cpp:35:37: warning:   by ‘folly::Optional<fizz::TLSMessage> {anonymous}::QuicEncryptedReadRecordLayer::read(folly::IOBufQueue&)’ [-Woverloaded-virtual]
quic/handshake/CMakeFiles/mvfst_handshake.dir/build.make:146: recipe for target 'quic/handshake/CMakeFiles/mvfst_handshake.dir/QuicFizzFactory.cpp.o' failed
make[2]: *** [quic/handshake/CMakeFiles/mvfst_handshake.dir/QuicFizzFactory.cpp.o] Error 1
CMakeFiles/Makefile2:3149: recipe for target 'quic/handshake/CMakeFiles/mvfst_handshake.dir/all' failed
make[1]: *** [quic/handshake/CMakeFiles/mvfst_handshake.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 11%] Building CXX object quic/codec/test/CMakeFiles/QuicConnectionIdTest.dir/__/__/common/test/TestMain.cpp.o
[ 11%] Building CXX object quic/codec/test/CMakeFiles/QuicIntegerTest.dir/__/__/common/test/TestMain.cpp.o
[ 12%] Linking CXX executable QuicConnectionIdTest
[ 13%] Building CXX object quic/codec/test/CMakeFiles/PacketNumberTest.dir/__/__/common/test/TestMain.cpp.o
[ 13%] Linking CXX executable QuicIntegerTest
[ 13%] Linking CXX executable PacketNumberTest
[ 13%] Built target QuicConnectionIdTest
[ 13%] Built target QuicIntegerTest
[ 13%] Built target PacketNumberTest
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2
```
***

**Comment by odelalleau** [comment]
Thanks for reporting this issue! I am actually going to release a major update to the code soon, which contains both algorithmic improvements and fixes to the build process. I'll make an early version available to you on Monday at the latest, so that you can try it out.

**Comment by odelalleau** [comment]
Actually, I was able to get an early version up now, you can try it out with the following steps:
```
# You should re-recreate your conda env:
conda activate base && conda env remove -n mvfst-rl && conda create -n mvfst-rl python=3.8 -y
conda activate mvfst-rl
# And re-synch the repo as well, grabbing the tmp_dev branch:
git clone -b tmp_dev https://github.com/facebookresearch/mvfst-rl mvfst-rl
cd mvfst-rl
./setup.sh
```
Please let me know how it goes! (it's been tested only on Ubuntu 20 and I wouldn't be surprised if there were still a few quirks depending on your exact setup).

**Comment by Zidan241** [comment]
@odelalleau thank you for the fast response, i set up an ubuntu 20.04 LTS VM and followed the steps in the comment above, however i faced this error:
this library 'git@github.com:fairinternal/nest.git' does not not exsist
***
```
Cloning into '/home/zidan/bachelor/mvfst-rl/third-party/torchbeast/third_party/nest'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:fairinternal/nest.git' into submodule path '/home/zidan/bachelor/mvfst-rl/third-party/torchbeast/third_party/nest' failed
Failed to clone 'third_party/nest'. Retry scheduled
Cloning into '/home/zidan/bachelor/mvfst-rl/third-party/torchbeast/third_party/nest'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:fairinternal/nest.git' into submodule path '/home/zidan/bachelor/mvfst-rl/third-party/torchbeast/third_party/nest' failed
Failed to clone 'third_party/nest' a second time, aborting
Failed to recurse into submodule path 'third-party/torchbeast'

```

**Comment by odelalleau** [comment]
Sorry about that, I missed that new Torchbeast dependency. Can you try again? (better delete your current mvfst-rl folder and re-clone it to start from a clean version)

**Comment by Zidan241** [comment]
@odelalleau, after a clean clone this error showed up:
```
Building wheels for collected packages: hydra-core
  Building wheel for hydra-core (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/zidan/anaconda3/envs/mvfst-rl/bin/python /home/zidan/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmphh0jsswa
       cwd: /tmp/pip-req-build-bddlywhk
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  running clean
  Generating parsers with antlr4
  running antlr
  Generating parser for Python3: ['java', '-jar', '/tmp/pip-req-build-bddlywhk/build_helpers/bin/antlr-4.8-complete.jar', '-Dlanguage=Python3', '-o', '/tmp/pip-req-build-bddlywhk/hydra/grammar/gen/', '-Xexact-output-dir', '-visitor', '/tmp/pip-req-build-bddlywhk/hydra/grammar/OverrideLexer.g4']
  /tmp/pip-build-env-4z1gryx9/overlay/lib/python3.8/site-packages/setuptools/dist.py:490: UserWarning: Normalizing '1.1.0dev6' to '1.1.0.dev6'
    warnings.warn(tmpl.format(**locals()))
  ===========================================================================
  | Unable to generate parsers: [Errno 2] No such file or directory: 'java' |
  ===========================================================================
  ----------------------------------------
  ERROR: Failed building wheel for hydra-core
Failed to build hydra-core
ERROR: Could not build wheels for hydra-core which use PEP 517 and cannot be installed directly
```
I really appreciate your help

**Comment by odelalleau** [comment]
Oh, thanks for reporting this, my system has java pre-installed so I didn't think of that. You can indeed install a system java, or if you want to minimize side effects, do it in conda with:
```
conda install -c bioconda java-jdk
```
(I'll probably add it in the Conda dependencies)

Note: in that case re-running `./setup.sh` should work, but just FYI, there are situations where if there is a crash during setup, and you fix the problem then re-run `./setup.sh`, it may skip the step that crashed due to seeing a folder that already exists. One example in Pantheon, because of this block:
```bash
  if [ -d "$PANTHEON_DIR" ]; then
    echo -e "$PANTHEON_DIR already exists, skipping."
    return
  fi
```

If you get yourself in such a situation, instead of re-cloning, you can run `./setup.sh --clean` which will do a clean re-install of everything.

**Comment by odelalleau** [comment]
Alright, so the first error is probably because it failed to detect your CUDA version. The corresponding code in setup.sh is:
```bash
  # Extract CUDA version (in format of the form 92 / 100 / 101 for instance)
  CUDA_VERSION=$(nvcc --version | \
                 grep -o "release [0-9]\+\.[0-9]\+," | \
                 sed "s/[release |,|\.]//g")

  # TorchBeast requires PyTorch with CUDA. This doesn't conflict with the
  # CPU-only libtorch installation as the install locations are different.
  echo -e "Installing PyTorch with CUDA (v$CUDA_VERSION) for TorchBeast"
  conda install -y numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses
  conda install -y -c pytorch magma-cuda$CUDA_VERSION
```

==> can you please tell me what is the output of `nvcc --version` on your system?
In the meantime, you can hardocde `CUDA_VERSION` in the script, e.g. CUDA_VERSION=110 for CUDA 11.0

The second error is probably because now you have the mm-* binaries copied to your conda env (from a previous run of ./setup.sh), and the --clean parameter doesn't actually delete them. This has been overlooked due to the fact I'm always using `--skip-mm-binaries` which skips that step. I'll look into it later, but in the meantime just add this flag to your setup (or, you could also re-create your conda env)

**Comment by Zidan241** [comment]
@odelalleau for i set CUDA_VERSION=110,
however ```nvcc --version``` showed that i did not have that installed, the VM i am using does not have CUDA support, is it necessary for training?

**Comment by odelalleau** [comment]
Ah, right now there are several things hardcoded for GPU. I’ll make sure to have a clearer error message when CUDA is missing.

The model remains small enough that it might be possible to run everything on CPU, but I’m afraid you’d need to figure this out by yourself (CPU-only support isn’t a priority right now). If you work on it I’m happy to provide support and take a PR.

Just to be clear, inference is on CPU but currently training requires GPU.

**Comment by odelalleau** [comment]
I had a closer look, training on CPU should actually be easy enough to achieve, by adding the two parameters:
```bash
learner_device=cpu inference_device=cpu
```

So it should just be a matter of compiling a CPU-only version of PyTorch in case CUDA isn't available.

At least, in theory :) I haven't actually tried it... so there might be surprises.

**Comment by Zidan241** [comment]
Build was successful, thanks a lot for your help, 
however, in training on a CPU machine, this error came up
and is it necessary to delete and re-install Pytorch for CPU training, or does it detects automatically?   
```
(mvfst-rl) zidan@general-8cpu-32mem-eu-vm1:~/bachelor/mvfst-rl$ python3 -m train.train learner_device=cpu inference_device=cpu
[DEBUG:1517 utils:228 2021-05-11 00:18:02,845] Setting JobRuntime:name=UNKNOWN_NAME
[DEBUG:1517 utils:228 2021-05-11 00:18:02,846] Setting JobRuntime:name=train
Traceback (most recent call last):
  File "/home/zidan/anaconda3/envs/mvfst-rl/lib/python3.8/pathlib.py", line 1287, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/zidan/mvfst-rl/run/2021-05-11_00-18-02'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zidan/anaconda3/envs/mvfst-rl/lib/python3.8/pathlib.py", line 1287, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/zidan/mvfst-rl/run'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zidan/anaconda3/envs/mvfst-rl/lib/python3.8/pathlib.py", line 1287, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/zidan/mvfst-rl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zidan/anaconda3/envs/mvfst-rl/lib/python3.8/pathlib.py", line 1287, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/zidan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zidan/anaconda3/envs/mvfst-rl/lib/python3.8/pathlib.py", line 1291, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/zidan/anaconda3/envs/mvfst-rl/lib/python3.8/pathlib.py", line 1291, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/home/zidan/anaconda3/envs/mvfst-rl/lib/python3.8/pathlib.py", line 1291, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  [Previous line repeated 1 more time]
  File "/home/zidan/anaconda3/envs/mvfst-rl/lib/python3.8/pathlib.py", line 1287, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/checkpoint'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by odelalleau** [comment]
Oh, also, it's great that you managed to build it on CPU only, would you mind please sharing how you compiled PyTorch? I could add this to the setup.sh script when CUDA isn't available.

**Comment by Zidan241** [comment]
while training, there seems to be a problem with the pantheon environment
```
ModuleNotFoundError: No module named 'subprocess_wrappers'
[WARNING:1599 pantheon_env:125 2021-05-11 23:06:54,948] Thread: 5 => process 2612 exited with return code 1
[INFO:1599 pantheon_env:115 2021-05-11 23:06:54,951] Thread: 5, episode: 38, experiment: 9, cmd: /home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/test.py local --data-dir /home/zidan/checkpoint/mvfst-rl/run/2021-05-11_23-06-43/train/train_tid5_run38_expt9 --pkill-cleanup --uplink-trace /home/zidan/bachelor/mvfst-rl/train/traces/12mbps.trace --downlink-trace /home/zidan/bachelor/mvfst-rl/train/traces/12mbps.trace --prepend-mm-cmds mm-delay 50 --extra-mm-link-args --uplink-queue=droptail --uplink-queue-args=packets=1 --downlink-queue=droptail --downlink-queue-args=packets=1 --schemes=mvfst_rl --run-times=1 --extra-sender-args="--cc_env_mode=remote --cc_env_rpc_address=unix:/tmp/rl_server_path_0 --cc_env_actor_id=5 --cc_env_job_id=9 --cc_env_model_file=/home/zidan/checkpoint/mvfst-rl/run/2021-05-11_23-06-43/traced_model.pt --cc_env_agg=time --cc_env_time_window_ms=100 --cc_env_fixed_window_size=10 --cc_env_use_state_summary=True --cc_env_history_size=20 --cc_env_norm_ms=100.0 --cc_env_norm_bytes=1000.0 --cc_env_actions=0,/2,-10,+10,*2 --cc_env_reward_log_ratio=True --cc_env_reward_throughput_factor=1.0 --cc_env_reward_throughput_log_offset=1e-05 --cc_env_reward_delay_factor=0.2 --cc_env_reward_delay_log_offset=1e-05 --cc_env_reward_packet_loss_factor=0.0 --cc_env_reward_packet_loss_log_offset=1e-05 --cc_env_reward_max_delay=True --cc_env_fixed_cwnd=10 --cc_env_min_rtt_window_length_us=10000000000 -v=1"
[WARNING:1599 pantheon_env:125 2021-05-11 23:06:54,953] Thread: 4 => process 2618 exited with return code 1
[INFO:1599 pantheon_env:115 2021-05-11 23:06:54,958] Thread: 4, episode: 47, experiment: 6, cmd: /home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/test.py local --data-dir /home/zidan/checkpoint/mvfst-rl/run/2021-05-11_23-06-43/train/train_tid4_run47_expt6 --pkill-cleanup --uplink-trace /home/zidan/bachelor/mvfst-rl/train/traces/12mbps.trace --downlink-trace /home/zidan/bachelor/mvfst-rl/train/traces/12mbps.trace --prepend-mm-cmds mm-delay 10 --extra-mm-link-args --uplink-queue=droptail --uplink-queue-args=packets=1 --downlink-queue=droptail --downlink-queue-args=packets=1 --schemes=mvfst_rl --run-times=1 --extra-sender-args="--cc_env_mode=remote --cc_env_rpc_address=unix:/tmp/rl_server_path_0 --cc_env_actor_id=4 --cc_env_job_id=6 --cc_env_model_file=/home/zidan/checkpoint/mvfst-rl/run/2021-05-11_23-06-43/traced_model.pt --cc_env_agg=time --cc_env_time_window_ms=100 --cc_env_fixed_window_size=10 --cc_env_use_state_summary=True --cc_env_history_size=20 --cc_env_norm_ms=100.0 --cc_env_norm_bytes=1000.0 --cc_env_actions=0,/2,-10,+10,*2 --cc_env_reward_log_ratio=True --cc_env_reward_throughput_factor=1.0 --cc_env_reward_throughput_log_offset=1e-05 --cc_env_reward_delay_factor=0.2 --cc_env_reward_delay_log_offset=1e-05 --cc_env_reward_packet_loss_factor=0.0 --cc_env_reward_packet_loss_log_offset=1e-05 --cc_env_reward_max_delay=True --cc_env_fixed_cwnd=10 --cc_env_min_rtt_window_length_us=10000000000 -v=1"
[WARNING:1599 pantheon_env:125 2021-05-11 23:06:54,964] Thread: 9 => process 2617 exited with return code 1
[INFO:1599 pantheon_env:115 2021-05-11 23:06:54,968] Thread: 9, episode: 5, experiment: 6, cmd: /home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/test.py local --data-dir /home/zidan/checkpoint/mvfst-rl/run/2021-05-11_23-06-43/train/train_tid9_run5_expt6 --pkill-cleanup --uplink-trace /home/zidan/bachelor/mvfst-rl/train/traces/12mbps.trace --downlink-trace /home/zidan/bachelor/mvfst-rl/train/traces/12mbps.trace --prepend-mm-cmds mm-delay 10 --extra-mm-link-args --uplink-queue=droptail --uplink-queue-args=packets=1 --downlink-queue=droptail --downlink-queue-args=packets=1 --schemes=mvfst_rl --run-times=1 --extra-sender-args="--cc_env_mode=remote --cc_env_rpc_address=unix:/tmp/rl_server_path_0 --cc_env_actor_id=9 --cc_env_job_id=6 --cc_env_model_file=/home/zidan/checkpoint/mvfst-rl/run/2021-05-11_23-06-43/traced_model.pt --cc_env_agg=time --cc_env_time_window_ms=100 --cc_env_fixed_window_size=10 --cc_env_use_state_summary=True --cc_env_history_size=20 --cc_env_norm_ms=100.0 --cc_env_norm_bytes=1000.0 --cc_env_actions=0,/2,-10,+10,*2 --cc_env_reward_log_ratio=True --cc_env_reward_throughput_factor=1.0 --cc_env_reward_throughput_log_offset=1e-05 --cc_env_reward_delay_factor=0.2 --cc_env_reward_delay_log_offset=1e-05 --cc_env_reward_packet_loss_factor=0.0 --cc_env_reward_packet_loss_log_offset=1e-05 --cc_env_reward_max_delay=True --cc_env_fixed_cwnd=10 --cc_env_min_rtt_window_length_us=10000000000 -v=1"
Traceback (most recent call last):
  File "/home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/test.py", line 15, in <module>
    import arg_parser
  File "/home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/arg_parser.py", line 7, in <module>
    from helpers import utils
  File "/home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/helpers/utils.py", line 16, in <module>
    from subprocess_wrappers import check_call, check_output, call
ModuleNotFoundError: No module named 'subprocess_wrappers'
Traceback (most recent call last):
  File "/home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/test.py", line 15, in <module>
    import arg_parser
  File "/home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/arg_parser.py", line 7, in <module>
    from helpers import utils
  File "/home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/helpers/utils.py", line 16, in <module>
    from subprocess_wrappers import check_call, check_output, call
ModuleNotFoundError: No module named 'subprocess_wrappers'
Traceback (most recent call last):
  File "/home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/test.py", line 15, in <module>
[WARNING:1599 pantheon_env:125 2021-05-11 23:06:54,982] Thread: 7 => process 2620 exited with return code 1
[INFO:1599 pantheon_env:115 2021-05-11 23:06:54,986] Thread: 7, episode: 20, experiment: 13, cmd: /home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/test.py local --data-dir /home/zidan/checkpoint/mvfst-rl/run/2021-05-11_23-06-43/train/train_tid7_run20_expt13 --pkill-cleanup --uplink-trace /home/zidan/bachelor/mvfst-rl/train/traces/12mbps.trace --downlink-trace /home/zidan/bachelor/mvfst-rl/train/traces/10-every-200.trace --prepend-mm-cmds mm-delay 10 --schemes=mvfst_rl --run-times=1 --extra-sender-args="--cc_env_mode=remote --cc_env_rpc_address=unix:/tmp/rl_server_path_0 --cc_env_actor_id=7 --cc_env_job_id=13 --cc_env_model_file=/home/zidan/checkpoint/mvfst-rl/run/2021-05-11_23-06-43/traced_model.pt --cc_env_agg=time --cc_env_time_window_ms=100 --cc_env_fixed_window_size=10 --cc_env_use_state_summary=True --cc_env_history_size=20 --cc_env_norm_ms=100.0 --cc_env_norm_bytes=1000.0 --cc_env_actions=0,/2,-10,+10,*2 --cc_env_reward_log_ratio=True --cc_env_reward_throughput_factor=1.0 --cc_env_reward_throughput_log_offset=1e-05 --cc_env_reward_delay_factor=0.2 --cc_env_reward_delay_log_offset=1e-05 --cc_env_reward_packet_loss_factor=0.0 --cc_env_reward_packet_loss_log_offset=1e-05 --cc_env_reward_max_delay=True --cc_env_fixed_cwnd=10 --cc_env_min_rtt_window_length_us=10000000000 -v=1"
    import arg_parser
  File "/home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/arg_parser.py", line 7, in <module>
    from helpers import utils
  File "/home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/helpers/utils.py", line 16, in <module>
    from subprocess_wrappers import check_call, check_output, call
```

**Comment by odelalleau** [comment]
Hmm, it's weird that it would work on my system but not yours. Do you get the same error if you write on the command line:
```bash
python2 /home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/test.py
```
?

**Comment by Zidan241** [comment]
I got this error, and it is the same for all other schemes
```
(mvfst-rl) zidan@general-8cpu-32mem-eu-vm1:~/bachelor/mvfst-rl$ python2 /home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/test.py local --all
$ /home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/git_summary.sh
Testing scheme fillp_sheep for experiment run 1/1...
$ /home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/wrappers/fillp_sheep.py run_first
[tunnel server manager (tsm)] $ python /home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/tunnel_manager.py
Traceback (most recent call last):
  File "/home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/tunnel_manager.py", line 10, in <module>
    from helpers import utils
  File "/home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/helpers/utils.py", line 16, in <module>
    from subprocess_wrappers import check_call, check_output, call
ModuleNotFoundError: No module named 'subprocess_wrappers'
WARNING: tunnel server manager terminated unexpectedly
Unable to run tunnel client or server manager => aborting
kill_proc_group: killed process group with pgid 1805
Error in testing scheme fillp_sheep with run ID 1
Testing scheme copa for experiment run 1/1...
$ /home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/wrappers/copa.py run_first
[tunnel server manager (tsm)] $ python /home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/tunnel_manager.py
Traceback (most recent call last):
  File "/home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/experiments/tunnel_manager.py", line 10, in <module>
    from helpers import utils
  File "/home/zidan/bachelor/mvfst-rl/_build/deps/pantheon/src/helpers/utils.py", line 16, in <module>
    from subprocess_wrappers import check_call, check_output, call
ModuleNotFoundError: No module named 'subprocess_wrappers'
WARNING: tunnel server manager terminated unexpectedly
Unable to run tunnel client or server manager => aborting
kill_proc_group: killed process group with pgid 1807
Error in testing scheme copa with run ID 1
Testing scheme indigo for experiment run 1/1...
```

**Comment by odelalleau** [comment]
Ok, I think it's using Python3 instead of Python2, can you run `which python2` to check where python2 is installed, then do a `ls -l` on the result but without the "2"? For instance:
```bash
> which python2
/usr/bin/python2
> ls -l /usr/bin/python
lrwxrwxrwx 1 root root 7 Apr 15  2020 /usr/bin/python -> python2
```

**Comment by odelalleau** [comment]
Ah, that's great! I'm going to close this issue then, but don't hesitate to open another one in case you run into more problems.
I'll also see if I can add a check during setup to raise a flag in case Python 2 isn't installed as expected.
