### ISSUE TITLE
'MvFstEnv' object has no attribute '_previous_obs_from_pantheon_process'

### ISSUE THREAD

**Issue by lishuo3331** [facebookresearch/mvfst-rl#30]
when i run the example command for running with a single gym-env,it raises this 
![image](https://user-images.githubusercontent.com/36464694/131464797-8d35b98c-270b-4622-92e0-849e2ca2f483.png)
my config.yaml:
defaults:
    - base_config
    - jobs@train_jobs: random_traces_0_5
    - jobs@eval_jobs: fixed_0_5
    - jobs@env_configs: fixed_0_5
    # - override hydra/launcher: _submitit_slurm
    - override hydra/launcher: _joblib

hydra:
    run:
        dir: checkpoint/${oc.env:USER}/mvfst-rl/run/${now:%Y-%m-%d_%H-%M-%S}
    sweep:
        dir: checkpoint/${oc.env:USER}/mvfst-rl/multirun/${now:%Y-%m-%d_%H-%M-%S}

**Comment by odelalleau** [comment]
Just to be sure, you are on commit c3d230f, correct?

It looks like the actual root of the error is elsewhere, because this error would be triggered by the Pantheon process dying unexpectedly (and this is what we need to debug). Would you be able to share the full stderr log?

**Comment by lishuo3331** [comment]
Sorry  just saw the message.
Yeah，it`s commit [c3d230f](https://github.com/facebookresearch/mvfst-rl/commit/c3d230f29ed86c96fc1987f18a36eac37f69dbf7)，’the full stderr log‘  you mean the shell output?
Shell:
```shell
[DEBUG:2293095 utils:252 2021-09-02 10:28:36,899] Setting JobRuntime:name=UNKNOWN_NAME
[DEBUG:2293095 utils:252 2021-09-02 10:28:36,900] Setting JobRuntime:name=example
[2021-09-02 10:28:37,218][root][INFO] - Deleting old RAM disk folder from PID 2292785: /dev/shm/mvfst-rl.tmp/16851ba9223c6b86677c95b6f246b38e865b5cae6cf3597ed8b952a948293a05
[2021-09-02 10:28:37,218][root][INFO] - Deleted dir (in 0.000s): /dev/shm/mvfst-rl.tmp/16851ba9223c6b86677c95b6f246b38e865b5cae6cf3597ed8b952a948293a05
[2021-09-02 10:28:37,219][root][WARNING] - Found a directory in RAM disk with no PID file
[2021-09-02 10:28:37,240][root][INFO] - Located python2 in /usr/local/bin
Error executing job with overrides: ['mode=train', 'jobs@env_configs=fixed_0_5', 'num_actors=1', 'env_ids=[0]', 'cc_env_norm_bytes=1000000', 'cc_env_norm_ms=10000', 'cc_env_history_size=16', 'cc_env_reward_delay_factor=0.75', 'cc_env_reward_packet_loss_factor=0', 'cc_env_reward_formula=log_ratio', 'cc_env_reward_delay_offset=0', 'cc_env_reward_min_throughput_ratio=0.9', 'cc_env_reward_n_packets_offset=1']
Traceback (most recent call last):
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/msi/Documents/mvfst-rl/gym_env/example.py", line 76, in <module>
    main()
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/msi/Documents/mvfst-rl/gym_env/example.py", line 71, in main
    play(flags)
  File "/home/msi/Documents/mvfst-rl/gym_env/example.py", line 63, in play
    play_with_single_env(flags)
  File "/home/msi/Documents/mvfst-rl/gym_env/example.py", line 29, in play_with_single_env
    env.reset()
  File "/home/msi/Documents/mvfst-rl/gym_env/env.py", line 125, in reset
    obs_from_pantheon_process, done = self._read_from_pantheon_observation_queue()
  File "/home/msi/Documents/mvfst-rl/gym_env/env.py", line 147, in _read_from_pantheon_observation_queue
    return (self._previous_obs_from_pantheon_process, done)
AttributeError: 'MvFstEnv' object has no attribute '_previous_obs_from_pantheon_process'
```

**Comment by odelalleau** [comment]
Oh, my bad, I forgot the interesting stderr would be hidden in the current implementation. Can you edit env.py at at line 110 replace ``stderr=subprocess.STDOUT,`` with ``stderr=None,``? I think you should now be able to see more output (and hopefully within it the real reason for the crash).

**Comment by lishuo3331** [comment]
The new shell output：
```shell
[DEBUG:2507822 utils:252 2021-09-03 20:48:41,218] Setting JobRuntime:name=UNKNOWN_NAME
[DEBUG:2507822 utils:252 2021-09-03 20:48:41,218] Setting JobRuntime:name=example
[2021-09-03 20:48:41,534][root][INFO] - Deleting old RAM disk folder from PID 2507449: /dev/shm/mvfst-rl.tmp/1613c45b0e445afdd74a385278d766ebd6a9ba8d8cae9566751c773f951b7e59
[2021-09-03 20:48:41,534][root][INFO] - Deleted dir (in 0.000s): /dev/shm/mvfst-rl.tmp/1613c45b0e445afdd74a385278d766ebd6a9ba8d8cae9566751c773f951b7e59
[2021-09-03 20:48:41,534][root][WARNING] - Found a directory in RAM disk with no PID file
[2021-09-03 20:48:41,535][root][WARNING] - Found a directory in RAM disk with no PID file
[2021-09-03 20:48:41,557][root][INFO] - Located python2 in /usr/local/bin
$ /home/msi/Documents/mvfst-rl/_build/deps/pantheon/src/experiments/git_summary.sh
Test PID 2507858: testing scheme mvfst_rl for experiment run 1/1...
$ /home/msi/Documents/mvfst-rl/_build/deps/pantheon/src/wrappers/mvfst_rl.py run_first
[tunnel server manager (tsm)] $ python /home/msi/Documents/mvfst-rl/_build/deps/pantheon/src/experiments/tunnel_manager.py
Test PID 2507858 / TSM PID 2507954: tunnel manager is running
[tunnel client manager (tcm)] prompt [tsm]
$ mm-delay 28 mm-loss uplink 0.0477 mm-link /home/msi/Documents/mvfst-rl/train/traces/0.57mbps-poisson.trace /home/msi/Documents/mvfst-rl/train/traces/0.57mbps-poisson.trace --uplink-log=/home/msi/Documents/mvfst-rl/checkpoint/msi/mvfst-rl/run/2021-09-03_20-48-41/train/train_tid0_expt0/mvfst_rl_mm_datalink_run1.log --downlink-log=/home/msi/Documents/mvfst-rl/checkpoint/msi/mvfst-rl/run/2021-09-03_20-48-41/train/train_tid0_expt0/mvfst_rl_mm_acklink_run1.log --uplink-queue=droptail --uplink-queue-args=packets=14 python /home/msi/Documents/mvfst-rl/_build/deps/pantheon/src/experiments/tunnel_manager.py
Died on std::runtime_error: dnsmasq: did not start after 20 attempts
Died on std::runtime_error: `packetshell': process exited with failure status 1
WARNING: tunnel client manager terminated unexpectedly
Unable to run tunnel client or server manager => aborting
kill_proc_group: killed process group with pgid 2507954
tunnel_manager: caught signal 15 and cleaned up

kill_proc_group: killing process 2507954
kill_proc_group: killed process group with pgid 2507955
kill_proc_group: killing process 2507955
Error in testing scheme mvfst_rl with run ID 1
All tests done!
Error executing job with overrides: ['mode=train', 'jobs@env_configs=fixed_0_5', 'num_actors=1', 'env_ids=[0]', 'cc_env_norm_bytes=1000000', 'cc_env_norm_ms=10000', 'cc_env_history_size=16', 'cc_env_reward_delay_factor=0.75', 'cc_env_reward_packet_loss_factor=0', 'cc_env_reward_formula=log_ratio', 'cc_env_reward_delay_offset=0', 'cc_env_reward_min_throughput_ratio=0.9', 'cc_env_reward_n_packets_offset=1']
Traceback (most recent call last):
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/msi/Documents/mvfst-rl/gym_env/example.py", line 76, in <module>
    main()
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/main.py", line 49, in decorated_main
    _run_hydra(
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 367, in _run_hydra
    run_and_report(
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    lambda: hydra.run(
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 110, in run
    _ = ret.return_value
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/msi/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/msi/Documents/mvfst-rl/gym_env/example.py", line 71, in main
    play(flags)
  File "/home/msi/Documents/mvfst-rl/gym_env/example.py", line 63, in play
    play_with_single_env(flags)
  File "/home/msi/Documents/mvfst-rl/gym_env/example.py", line 29, in play_with_single_env
    env.reset()
  File "/home/msi/Documents/mvfst-rl/gym_env/env.py", line 126, in reset
    obs_from_pantheon_process, done = self._read_from_pantheon_observation_queue()
  File "/home/msi/Documents/mvfst-rl/gym_env/env.py", line 148, in _read_from_pantheon_observation_queue
    return (self._previous_obs_from_pantheon_process, done)
AttributeError: 'MvFstEnv' object has no attribute '_previous_obs_from_pantheon_process'
```
Actually, I previously suspected that there was some problems in Pantheon itself.I followed the test example in 
the repository of the Pantheon  and got the same bug : "dnsmasq: did not start after 20 attempts". I am looking for a solution in Pantheon `s google group. It is possible that this bug has nothing to do with mvfst-rl.

**Comment by odelalleau** [comment]
Ah! I've seen that error before but only when running many envs in parallel, which can cause too much load. The only advice I can provide is to cleanup all processes on your machine... but if it doesn't work I'm afraid I can't help much. This issue might provide some hints (?) https://github.com/ravinet/mahimahi/issues/143

**Comment by lishuo3331** [comment]
Thanks, I will try this solution.

**Comment by odelalleau** [comment]
I am going to close this issue since it seems like it wasn't directly related to the mvfst-rl code, but feel free to reopen if you need to follow-up on it.
