### ISSUE TITLE
mvfst-rl/_build/build/traffic_gen/traffic_gen: undefined symbol: _ZNK6google8protobuf7Message25InitializationErrorStringB5cxx11Ev 

### ISSUE THREAD

**Issue by xhcx** [facebookresearch/mvfst-rl#40]
Hi ：
when i run: “python3 -m train.train mode=train total_steps=100 num_actors=2 hydra.run.dir=/tmp/logs ” met some trouble：it seem do training and local test successfully（show in the following log file(1): /tmp/logs/train.log） 
but actually i see some running error(but hasn't interrupt running) in terminal output log(2). i check protobuf has been installed(version is 3.8.0) ，looking forward to your help！

~which protoc： 
/home/wang/anaconda3/bin/protoc
~protoc --version
libprotoc 3.8.0

1、/tmp/logs/train.log：
[2022-04-26 14:10:13,971][root][INFO] - Deleted dir (in 0.009s): /dev/shm/mvfst-rl.tmp/f9c4817dd8e9684cbdbfcc4e174d6ff7117a83631d0cd2d7ec86521a2fb748de
[2022-04-26 14:10:42,891][root][INFO] - Mode=train
[2022-04-26 14:10:43,600][root][INFO] - Deleted dir (in 0.000s): /dev/shm/mvfst-rl.tmp/f9c4817dd8e9684cbdbfcc4e174d6ff7117a83631d0cd2d7ec86521a2fb748de
[2022-04-26 14:10:43,601][root][INFO] - Starting agent 0. Mode=train, logdir=/tmp/logs/train
[2022-04-26 14:10:45,904][root][INFO] - Stop event #0 set, will kill corresponding env (pid=29404)
[2022-04-26 14:10:46,627][root][INFO] - Done training.
[2022-04-26 14:10:46,627][root][INFO] - Deleted dir (in 0.000s): /dev/shm/mvfst-rl.tmp/f9c4817dd8e9684cbdbfcc4e174d6ff7117a83631d0cd2d7ec86521a2fb748de
[2022-04-26 14:10:46,722][root][INFO] - Missing traced model, tracing first
[2022-04-26 14:10:46,735][root][INFO] - Deleted dir (in 0.000s): /dev/shm/mvfst-rl.tmp/f9c4817dd8e9684cbdbfcc4e174d6ff7117a83631d0cd2d7ec86521a2fb748de
[2022-04-26 14:10:46,735][root][INFO] - Tracing model from checkpoint /tmp/logs/checkpoint.tar
[2022-04-26 14:10:47,774][root][INFO] - Done tracing to /tmp/logs/traced_model.pt
[2022-04-26 14:10:47,775][root][INFO] - Deleted dir (in 0.000s): /dev/shm/mvfst-rl.tmp/f9c4817dd8e9684cbdbfcc4e174d6ff7117a83631d0cd2d7ec86521a2fb748de
[2022-04-26 14:10:47,775][root][INFO] - Starting local test, logdir=/tmp/logs/test
[2022-04-26 14:54:26,930][root][INFO] - Done local test
[2022-04-26 14:54:26,930][root][INFO] - All done! Checkpoint: /tmp/logs/checkpoint.tar, traced model: /tmp/logs/traced_model.pt

2、terminal log：
/home/wang/WorkSpace/RL/mvfst-rl/_build/deps/pantheon/third_party/mvfst-rl/_build/build/traffic_gen/traffic_gen: symbol lookup error: /home/wang/WorkSpace/RL/mvfst-rl/_build/deps/pantheon/third_party/mvfst-rl/_build/build/traffic_gen/traffic_gen: undefined symbol: _ZNK6google8protobuf7Message25InitializationErrorStringB5cxx11Ev
Traceback (most recent call last):
  File "/home/wang/WorkSpace/RL/mvfst-rl/_build/deps/pantheon/src/wrappers/mvfst_rl.py", line 139, in <module>
    main()
  File "/home/wang/WorkSpace/RL/mvfst-rl/_build/deps/pantheon/src/wrappers/mvfst_rl.py", line 118, in main
    assert p.wait() == 0, "Command failed: {}".format(" ".join(cmd))
AssertionError: Command failed: /home/wang/WorkSpace/RL/mvfst-rl/_build/deps/pantheon/third_party/mvfst-rl/_build/build/traffic_gen/traffic_gen --mode=server --host=0.0.0.0 --port=35673 --cc_algo=rl --cc_env_mode=local --cc_env_rpc_address=unix:/tmp/rl_server_path_0 --cc_env_actor_id=0 --cc_env_job_count=-1 --cc_env_model_file=/tmp/logs/traced_model.pt --cc_env_agg=time --cc_env_time_window_ms=100 --cc_env_fixed_window_size=10 --cc_env_use_state_summary=True --cc_env_history_size=20 --cc_env_norm_ms=100.0 --cc_env_norm_bytes=1000.0 --cc_env_actions=0,/2,-10,+10,*2 --cc_env_uplink_bandwidth=0.069 --cc_env_uplink_queue_size_bytes=21000 --cc_env_base_rtt=56 --cc_env_reward_delay_offset=0.0 --cc_env_reward_formula=log_ratio --cc_env_reward_throughput_factor=1.0 --cc_env_reward_throughput_log_offset=1e-05 --cc_env_reward_delay_factor=0.2 --cc_env_reward_delay_log_offset=1e-05 --cc_env_reward_packet_loss_factor=0.0 --cc_env_reward_packet_loss_log_offset=1e-05 --cc_env_reward_min_throughput_ratio=0.9 --cc_env_reward_max_throughput_ratio=1.0 --cc_env_reward_n_packets_offset=1.0 --cc_env_reward_uplink_queue_max_fill_ratio=0.5 --cc_env_reward_max_delay=True --cc_env_fixed_cwnd=10 --cc_env_min_rtt_window_length_us=10000000000 --cc_env_rtt_noise_std=0.0 --cc_env_ack_delay_avg_coeff=0.1 --cc_env_bandwidth_min_window_duration_ms=100 --cc_env_obs_scaling=1.0 --cc_env_stats_file= -v=1
[INFO:29637 pantheon_env:609 2022-04-26 14:10:49,518] Using all 6 jobs.
[INFO:29637 pantheon_env:624 2022-04-26 14:10:49,523] Located python2 in /usr/bin
[DEBUG:29637 pantheon_env:341 2022-04-26 14:10:49,527] Sampled job with target cwnd: 39.07987220447284

**Comment by xhcx** [comment]
there also no mvfst-rl's data in pantheon_report.pdf

Run 1: Statistics of mvfst-rl
Start at: 2022-04-26 06:10:57
End at: 2022-04-26 06:11:27

Run 1: Report of mvfst-rl | Data Link
Figure is missing
Figure is missing

**Comment by odelalleau** [comment]
Sorry I have very limited bandwidth to support you with this issue at this time.

My first guess would be a mismatch between the protobuf version that was used at compile time (controlled through the CPATH — for includes — and LIBRARY_PATH — for the .so — variables) and the one that is being used when the program is executed (controlled through the LD_LIBRARY_PATH variable).

I would try to see if something comes up when running ldd on traffic_gen, and otherwise try to reproduce the issue by running traffic_gen in the terminal (then mess with LD_LIBRARY_PATH to try to make it work).


Note that the mvfst-rl wrapper in Pantheon should be calling a function that modifies LD_LIBRARY_PATH, see https://github.com/odelalleau/pantheon/blob/751a054e2b64349b50f25967d36a030ca8f992f5/src/wrappers/mvfst_rl.py#L91

Hope this helps!

**Comment by xhcx** [comment]
really appreciate your reply and help！it is ok now
maybe i make a mistake：run “python3 -m train.train mode=train total_steps=100 num_actors=2 hydra.run.dir=/tmp/logs”in a new terminal without run "conda activate mvfst-rl" first
