### ISSUE TITLE
setup error with sprout.

### ISSUE THREAD

**Issue by yhcchaos** [facebookresearch/mvfst-rl#42]
Hello! 
when I run ./setup.sh, the following error occurs when building sprout:
gcc version = 7.5.0
Thanks very much if you can give me some advice to solve this problem.

collect2: error: ld returned 1 exit status
Makefile:375: recipe for target 'ntester' failed
make[3]: *** [ntester] Error 1
make[3]: Leaving directory '/root/Congestion_RL/mvfst-rl/_build/deps/pantheon/third_party/sprout/src/examples'
Makefile:341: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/root/Congestion_RL/mvfst-rl/_build/deps/pantheon/third_party/sprout/src'
Makefile:386: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/Congestion_RL/mvfst-rl/_build/deps/pantheon/third_party/sprout'
Makefile:327: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "/root/Congestion_RL/mvfst-rl/_build/deps/pantheon/src/wrappers/sprout.py", line 54, in <module>
    main()
  File "/root/Congestion_RL/mvfst-rl/_build/deps/pantheon/src/wrappers/sprout.py", line 35, in main
    check_call(sh_cmd, shell=True, cwd=cc_repo)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command './autogen.sh && ./configure --enable-examples && make -j' returned non-zero exit status 2
Traceback (most recent call last):
  File "./src/experiments/setup.py", line 59, in <module>
    main()
  File "./src/experiments/setup.py", line 55, in main
    setup(args)
  File "./src/experiments/setup.py", line 45, in setup
    check_call([cc_src, 'setup'])
  File "/root/Congestion_RL/mvfst-rl/_build/deps/pantheon/src/helpers/subprocess_wrappers.py", line 24, in check_call
    return subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/root/Congestion_RL/mvfst-rl/_build/deps/pantheon/src/wrappers/sprout.py', 'setup']' returned non-zero exit status 1

**Comment by odelalleau** [comment]
Since this codebase is not supported anymore, I’m afraid you’d need to figure out by yourself how to build sprout on your system.

The easiest workaround is probably just to skip sprout by removing it from this line: https://github.com/facebookresearch/mvfst-rl/blob/778bc4259ae7277e67c2ead593a493845c93db83/setup.sh#L251

Note that since the setup crashed you may need to re-run it with --clean to do a clean new attempt.

**Comment by yhcchaos** [comment]
okay, thanks.
